SRC += features/achordion.c

AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
VIA_ENABLE = no
TAP_DANCE_ENABLE = no
LEADER_ENABLE = no
COMBO_ENABLE = no
BOOTMAGIC_ENABLE = yes
